# Author: Ahmed Alaa Gomaa Mohammed
# Id: 20201701804

# I'm not responsible for any mistakes in the output uel pdfs
# checking the coorectness of all data in the output pdfs is the users responsibility

## csv
# columns start from 1
name_column = 1
id_column = 2
mark_column = 3
final_mark_column = 4 # only first row is used, if you mess this one up then you are screwed

# you can get the co-ordinates from https://pdflite.co/simplified-pdf-viewer/index.html
# or use pdfbox which is my preferred https://pdfbox.apache.org/download.cgi


## student field
name_postion = [x, y]
id_postion = [x, y]
student_field_font_size = 16

## horizontal checkmark field
horizontal_marks = [100, 96, 93, 90, 89, 84, 79, 75, 74, 69, 60, 59, 40, 20, 0]
# horizontal_marks = [100, 96, 92, 89, 88, 84, 80, 76, 75, 72, 69, 67, 66, 64, 62, 60, 59, 40, 20, 0]
horizontal_postions = [
    [x, y], # only the first y co-ordinates is need, the rest can be zeros
    [x, 0],
    [x, 0],
    [x, 0],
    [x, 0],
    [x, 0],
    [x, 0],
    [x, 0],
    [x, 0],
    [x, 0],
    [x, 0],
    [x, 0],
    [x, 0],
    [x, 0],
    [x, 0],
    [x, 0],
#   [x, 0],
#   [x, 0],
#   [x, 0],
#   [x, 0],
]
horizontal_feild_font_size = 14

## grade field
first_marker_postion  = [x, y]
second_marker_postion = [x, y]
asu_mark_postion = [x, y]
uel_mark_postion = [x, y]
grade_field_font_size = 14

## vertical checkmark field
vertical_marks = [[100, 100], [95, 97], [82, 93], [70, 89], [66, 84], [63, 80], [60, 76], [56, 73], [53, 70], [50, 67], [45, 64], [40, 60]] # do not edit this
vertical_postions = [
    [x, y], # only the first x co-ordinates is need, the rest can be zeros
    [0, y],
    [0, y],
    [0, y],
    [0, y],
    [0, y],
    [0, y],
    [0, y],
    [0, y],
    [0, y],
    [0, y],
    [0, y],
]
vertical_feild_font_size = 12
